"""initial schema aligned with sqlite

Revision ID: 529298d9839d
Revises: 
Create Date: 2026-07-18 13:36:38.569391

"""
import sys
from pathlib import Path

# 将 server 目录加入 sys.path，确保 alembic 加载迁移脚本时能导入 app 包
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '529298d9839d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verify_code', sa.String(length=10), nullable=True),
    sa.Column('email_verify_expires_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('plan_expires_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("plan IN ('free', 'single', 'subscription')", name='ck_users_plan'),
    sa.CheckConstraint('email_verified IN (0, 1)', name='ck_users_email_verified'),
    sa.CheckConstraint('is_admin IN (0, 1)', name='ck_users_is_admin'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('openid')
    )
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_openid', 'users', ['openid'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'inspected', 'hypothesized', 'simulated', 'analyzed')", name='ck_projects_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_deleted_at', 'projects', ['deleted_at'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_index('idx_projects_user_id_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_table('correlation_matrices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_correlation_matrices_deleted_at', 'correlation_matrices', ['deleted_at'], unique=False)
    op.create_index('idx_correlation_matrices_project_id', 'correlation_matrices', ['project_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hypotheses_deleted_at', 'hypotheses', ['deleted_at'], unique=False)
    op.create_index('idx_hypotheses_project_id', 'hypotheses', ['project_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'paid', 'refunded', 'cancelled')", name='ck_orders_status'),
    sa.CheckConstraint("type IN ('single', 'subscription')", name='ck_orders_type'),
    sa.CheckConstraint('amount >= 0', name='ck_orders_amount'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_transaction_id')
    )
    op.create_index('idx_orders_deleted_at', 'orders', ['deleted_at'], unique=False)
    op.create_index('idx_orders_project_id', 'orders', ['project_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('is_reverse', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("confidence IN ('high', 'low')", name='ck_questions_confidence'),
    sa.CheckConstraint("question_type IN ('likert5', 'likert7', 'demographic', 'other')", name='ck_questions_question_type'),
    sa.CheckConstraint('is_reverse IN (0, 1)', name='ck_questions_is_reverse'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'index')
    )
    op.create_index('idx_questions_deleted_at', 'questions', ['deleted_at'], unique=False)
    op.create_index('idx_questions_project_id', 'questions', ['project_id'], unique=False)
    op.create_table('hypothesis_paths',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=False),
    sa.Column('predictor', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.String(length=10), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("direction IN ('positive', 'negative')", name='ck_hypothesis_paths_direction'),
    sa.CheckConstraint("strength IN ('weak', 'medium', 'strong')", name='ck_hypothesis_paths_strength'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hypothesis_paths_deleted_at', 'hypothesis_paths', ['deleted_at'], unique=False)
    op.create_index('idx_hypothesis_paths_hypothesis_id', 'hypothesis_paths', ['hypothesis_id'], unique=False)
    op.create_table('simulation_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=True),
    sa.Column('matrix_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('sample_size > 0', name='ck_simulation_configs_sample_size'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matrix_id'], ['correlation_matrices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simulation_configs_deleted_at', 'simulation_configs', ['deleted_at'], unique=False)
    op.create_index('idx_simulation_configs_hypothesis_id', 'simulation_configs', ['hypothesis_id'], unique=False)
    op.create_index('idx_simulation_configs_matrix_id', 'simulation_configs', ['matrix_id'], unique=False)
    op.create_index('idx_simulation_configs_project_id', 'simulation_configs', ['project_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_config_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('sample_size > 0', name='ck_datasets_sample_size'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_config_id'], ['simulation_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_config_id')
    )
    op.create_index('idx_datasets_deleted_at', 'datasets', ['deleted_at'], unique=False)
    op.create_index('idx_datasets_project_id', 'datasets', ['project_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('overall_alpha', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_dataset_id', 'reports', ['dataset_id'], unique=False)
    op.create_index('idx_reports_deleted_at', 'reports', ['deleted_at'], unique=False)
    op.create_index('idx_reports_project_id', 'reports', ['project_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('passed IN (0, 1)', name='ck_diagnoses_passed'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index('idx_diagnoses_deleted_at', 'diagnoses', ['deleted_at'], unique=False)
    op.create_index('idx_diagnoses_report_id', 'diagnoses', ['report_id'], unique=False)
    op.create_table('reliability_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('alpha', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('kmo', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('bartlett_p_value', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('passed IN (0, 1)', name='ck_reliability_results_passed'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'dimension')
    )
    op.create_index('idx_reliability_results_deleted_at', 'reliability_results', ['deleted_at'], unique=False)
    op.create_index('idx_reliability_results_report_id', 'reliability_results', ['report_id'], unique=False)
    op.create_table('diagnosis_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diagnosis_issues_deleted_at', 'diagnosis_issues', ['deleted_at'], unique=False)
    op.create_index('idx_diagnosis_issues_diagnosis_id', 'diagnosis_issues', ['diagnosis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_diagnosis_issues_diagnosis_id', table_name='diagnosis_issues')
    op.drop_index('idx_diagnosis_issues_deleted_at', table_name='diagnosis_issues')
    op.drop_table('diagnosis_issues')
    op.drop_index('idx_reliability_results_report_id', table_name='reliability_results')
    op.drop_index('idx_reliability_results_deleted_at', table_name='reliability_results')
    op.drop_table('reliability_results')
    op.drop_index('idx_diagnoses_report_id', table_name='diagnoses')
    op.drop_index('idx_diagnoses_deleted_at', table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index('idx_reports_project_id', table_name='reports')
    op.drop_index('idx_reports_deleted_at', table_name='reports')
    op.drop_index('idx_reports_dataset_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_datasets_project_id', table_name='datasets')
    op.drop_index('idx_datasets_deleted_at', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('idx_simulation_configs_project_id', table_name='simulation_configs')
    op.drop_index('idx_simulation_configs_matrix_id', table_name='simulation_configs')
    op.drop_index('idx_simulation_configs_hypothesis_id', table_name='simulation_configs')
    op.drop_index('idx_simulation_configs_deleted_at', table_name='simulation_configs')
    op.drop_table('simulation_configs')
    op.drop_index('idx_hypothesis_paths_hypothesis_id', table_name='hypothesis_paths')
    op.drop_index('idx_hypothesis_paths_deleted_at', table_name='hypothesis_paths')
    op.drop_table('hypothesis_paths')
    op.drop_index('idx_questions_project_id', table_name='questions')
    op.drop_index('idx_questions_deleted_at', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_project_id', table_name='orders')
    op.drop_index('idx_orders_deleted_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_hypotheses_project_id', table_name='hypotheses')
    op.drop_index('idx_hypotheses_deleted_at', table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index('idx_correlation_matrices_project_id', table_name='correlation_matrices')
    op.drop_index('idx_correlation_matrices_deleted_at', table_name='correlation_matrices')
    op.drop_table('correlation_matrices')
    op.drop_index('idx_projects_user_id_status', table_name='projects')
    op.drop_index('idx_projects_user_id', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_deleted_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_users_openid', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_deleted_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
