"""initial tables

Revision ID: dfbbbf4dfadf
Revises:
Create Date: 2026-07-08 11:41:47.668765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dfbbbf4dfadf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('user_id', sa.String(36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_table('correlation_matrices',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_correlation_matrices_project_id', 'correlation_matrices', ['project_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hypotheses_project_id', 'hypotheses', ['project_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('user_id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_project_id', 'orders', ['project_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('is_reverse', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_project_id', 'questions', ['project_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=False),
    sa.Column('overall_alpha', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_project_id', 'reports', ['project_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('report_id', sa.String(36), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index('idx_diagnoses_report_id', 'diagnoses', ['report_id'], unique=True)
    op.create_table('hypothesis_paths',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('hypothesis_id', sa.String(36), nullable=False),
    sa.Column('predictor', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hypothesis_paths_hypothesis_id', 'hypothesis_paths', ['hypothesis_id'], unique=False)
    op.create_table('reliability_results',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('report_id', sa.String(36), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('alpha', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('kmo', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('bartlett_p_value', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reliability_results_report_id', 'reliability_results', ['report_id'], unique=False)
    op.create_table('simulation_configs',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.String(36), nullable=True),
    sa.Column('matrix_id', sa.String(36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['matrix_id'], ['correlation_matrices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simulation_configs_project_id', 'simulation_configs', ['project_id'], unique=False)
    op.create_table('diagnosis_issues',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('diagnosis_id', sa.String(36), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diagnosis_issues_diagnosis_id', 'diagnosis_issues', ['diagnosis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_diagnosis_issues_diagnosis_id', table_name='diagnosis_issues')
    op.drop_table('diagnosis_issues')
    op.drop_index('idx_simulation_configs_project_id', table_name='simulation_configs')
    op.drop_table('simulation_configs')
    op.drop_index('idx_reliability_results_report_id', table_name='reliability_results')
    op.drop_table('reliability_results')
    op.drop_index('idx_hypothesis_paths_hypothesis_id', table_name='hypothesis_paths')
    op.drop_table('hypothesis_paths')
    op.drop_index('idx_diagnoses_report_id', table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index('idx_reports_project_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_questions_project_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_project_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_hypotheses_project_id', table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index('idx_correlation_matrices_project_id', table_name='correlation_matrices')
    op.drop_table('correlation_matrices')
    op.drop_index('idx_projects_user_id', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
